---
- hosts: vagrant
  become: true
  user: vagrant
  vars_files:
    - secret_vars.yml
  roles:
    - debian_common
    - pt
    # - mackerel
    - pre_odango

- hosts: vagrant
  become: true
  user: chinachu
  roles:
    - docker

