---
- name: add modprobe
  blockinfile:
    dest: /etc/modprobe.d/blacklist.conf
    create: yes
    content: |
      blacklist earth-pt1
      blacklist earth-pt3
  tags: driver

- name: clone driver repository
  git:
    repo=https://github.com/m-tsudo/pt3.git
    dest={{ pt3_driver_path }}
    version={{ pt3_driver_version }}
  tags: driver

- name: make driver
  command:
    make
    chdir={{ pt3_driver_path }}
  tags: driver

- name: make install driver
  command:
    make install
    chdir={{ pt3_driver_path }}
  tags: driver

- name: install dkms
  apt: name=dkms
  tags: driver

- name: enable dkms for pt3 driver
  command:
    ${SHELL} ./dkms.install
    chdir={{ pt3_driver_path }}
  tags: driver

- name: remove pcscd
  apt:
    name=pcscd
    state=absent
  tags: remove-pcscd

#- name: reboot
#  shell: "sleep 2s && /sbin/reboot"
#  async: 1
#  poll: 0
#  tags: driver

#- name: wait for the server to come up
#  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
#  tags: driver
#
- name: reboot vagrant host
  command: vagrant reload
  delegate_to: 127.0.0.1
  become: false
  changed_when: false

- name: check the pt3 device
  stat: path=/dev/pt3video0
  register: pt3
  tags: driver

#- fail: msg="/dev/pt3video0 does not found"
#  when: not pt3.stat.exists

